#pragma once

#define TESTMAIN_SIZE_MEMORYREQUESTED 100000
#define TESTMAIN_SIZE_MEMORYVARIABLE TESTMAIN_SIZE_MEMORYREQUESTED/2
#define TESTMAIN_COUNT_TESTEXCEPTION 10
#define TESTMAIN_COUNT_TESTLOG 10

#define COUNT_TESTSUITES 20
#define COUNT_TESTCASES 20


